#include "stdafx.h"

#pragma comment(lib, "zstd_x64.lib")
#pragma comment(lib, "cq_stdlib_x64.lib")
#pragma comment(lib, "dalr_x64.lib")
#pragma comment(lib, "util_x64.lib")
#pragma comment(lib, "mapdal_server_x64.lib")
#pragma comment(lib, "sqlite3_x64.lib")
#pragma comment(lib, "base_x64.lib")
#pragma comment(lib, "auth_x64.lib")
#pragma comment(lib, "math3d_x64.lib")
#pragma comment(lib, "ws2_32.lib")
#pragma comment(lib, "dbghelp.lib")
#pragma comment(lib, "winmm.lib")
#pragma comment(lib, "math3d_x64.lib")
#pragma comment(lib, "render_system_x64.lib")
#pragma comment(lib, "protobuf_x64.lib")
#pragma comment(lib, "navi_rds_x64.lib")
